# Generated by Django 2.1.4 on 2018-12-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.SmallIntegerField()),
                ('raw_text', models.TextField()),
                ('cleaned_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacebookStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stories.story',),
        ),
        migrations.CreateModel(
            name='InstagramStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stories.story',),
        ),
        migrations.CreateModel(
            name='TwitterStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stories.story',),
        ),
    ]
