# Generated by Django 2.1.4 on 2018-12-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
        ('stories', '0002_story_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='names.Name'),
        ),
    ]
